######################################################################
##
## Filename: counter_tb.udo
## Created on: Tue Feb 07 4:15:24 PM Mountain Standard Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
