######################################################################
##
## Filename: counter.udo
## Created on: Mon Feb 06 6:43:46 PM Mountain Standard Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
