#Simple, brute force makefile for the complex project

complex: complex.c complex.h complex-functions.c
	gcc complex.c complex-functions.c -lm -o complex

#Silently try to remove all byproducts
clean:
	rm -f complex
