#Simple, brute force makefile for the complex project

driver: testdriver.cpp FinancialAidAward.cpp StudentAidRecord.cpp
	g++ testdriver.cpp FinancialAidAward.cpp StudentAidRecord.cpp -o driver

#Silently try to remove all byproducts
clean:
	rm -f driver
